########Turn On Porch and Front Room if motion detected########
alias: Turn On porch and Front Room if motion is detected 1hr before sunset until sunrise.
trigger:
- platform: state
  entity_id: binary_sensor.ring_front_door_motion
  to: 'on'
condition:
  condition: sun
  after: sunset
  after_offset: "-0:30:00"  
action:
  service: switch.turn_on
  entity_id: switch.front_room_ceiling_switch, switch.porch_switch, switch.front_room_switch