- platform: ring
  monitored_conditions:
    - ding
    - motion


- platform: mqtt
  state_topic: "smartthings/Andrea Status/contact"
  name: Andrea Bedroom Window
  payload_on: "open"
  payload_off: "closed"
  device_class: opening

- platform: mqtt
  state_topic: "smartthings/Brendan Status/contact"
  name: Brendan Bedroom Window
  payload_on: "open"
  payload_off: "closed"
  device_class: opening

- platform: mqtt
  state_topic: "smartthings/Downstairs Back Door/contact"
  name: Back Door
  payload_on: "open"
  payload_off: "closed"
  device_class: opening

- platform: mqtt
  state_topic: "smartthings/Front Door Deadbolt/contact"
  name: Front Door Deadbolt
  payload_on: "open"
  payload_off: "closed"
  device_class: opening

- platform: mqtt
  state_topic: "smartthings/Garage Door/contact"
  name: Garage Door
  payload_on: "open"
  payload_off: "closed"
  device_class: opening

- platform: mqtt
  state_topic: "smartthings/Inside Lock Status/contact"
  name: Inside Lock
  payload_on: "open"
  payload_off: "closed"
  device_class: opening

- platform: mqtt
  state_topic: "smartthings/Master Bedroom Status/contact"
  name: Master Bedroom Window
  payload_on: "open"
  payload_off: "closed"
  device_class: opening
