######## NOTIFICATIONS ########

######## SLACK NOTIFICATION PLATFORM ########
- platform: slack
  name: slack
  api_key: !secret slack_api_key
  default_channel: '#general'

######## SENDGRID NOTIFICATION PLATFORM ROBERT ########
- platform: sendgrid
  name: sendgrid_robert
  api_key: !secret sendgrid_api_key
  sender: !secret sendgrid_robert_email
  recipient: !secret sendgrid_robert_sms

######## SENDGRID NOTIFICATION PLATFORM KELLIE ########
- platform: sendgrid
  name: sendgrid_kellie
  api_key: !secret sendgrid_api_key
  sender: !secret sendgrid_robert_email
  recipient: !secret sendgrid_kellie_sms