######## SENSORS ########

######## DARKSKY WEATHER SENSOR ########
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - wind_speed

######## SPEEDTEST SENSOR ########
- platform: speedtest
  scan_interval: 300
  monitored_conditions:
    - ping
    - download
    - upload

######## PI SYSTEM MONITOR SENSOR ########
- platform: systemmonitor
  scan_interval: 300
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

######## HOMEAUTOMATION PI MONITOR SENSOR ########
- platform: netdata
  scan_interval: 300
  name: HomeAutomation NetData
  resources:
    - memory_free
    - memory_used
    - memory_cached
    - memory_buffers
    - swap_free
    - swap_used
    - processes_running
    - processes_blocked
    - system_load
    - system_io_in
    - system_io_out

######## NEST SENSOR ########
- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'
    - 'humidity'
    - 'operation_mode'

######## FRONT DOOR LOCK BATTERY SENSOR ########    
- platform: mqtt
  state_topic: "smartthings/Front Door Deadbolt/battery"
  unit_of_measurement: "%"
  retain: true

######## GAMER GLANCES REST MONITORING ########
- platform: rest
  scan_interval: 300
  resource: !secret gamer_glances
  name: Gamer CPU Use
  unit_of_measurement: '%'
  value_template: '{{ value_json.cpu.total }}'

- platform: rest
  scan_interval: 300
  resource: !secret gamer_glances
  name: Gamer RAM Free
  unit_of_measurement: MB
  value_template: '{{ value_json.mem.free | multiply(0.000000954) | round(0) }}'

- platform: rest
  scan_interval: 300
  resource: !secret gamer_glances
  name: 'Gamer C:'
  unit_of_measurement: '%'
  value_template: '{{ value_json.fs[0].percent }}'

- platform: rest
  scan_interval: 300
  resource: !secret gamer_glances
  name: 'Gamer D:'
  unit_of_measurement: '%'
  value_template: '{{ value_json.fs[1].percent }}'

######## MEDIACENTER GLANCES REST MONITORING ########
- platform: rest
  scan_interval: 300
  resource: !secret mediacenter_glances
  name: MediaCenter CPU Use
  unit_of_measurement: '%'
  value_template: '{{ value_json.cpu.total }}'

- platform: rest
  scan_interval: 300
  resource: !secret mediacenter_glances
  name: MediaCenter RAM Free
  unit_of_measurement: MB
  value_template: '{{ value_json.mem.free | multiply(0.000000954) | round(0) }}'

- platform: rest
  scan_interval: 300
  resource: !secret mediacenter_glances
  name: 'MediaCenter C:'
  icon: mdi:harddisk
  unit_of_measurement: '%'
  value_template: '{{ value_json.fs[0].percent }}'

- platform: rest
  scan_interval: 300
  resource: !secret mediacenter_glances
  name: 'MediaCenter Movies'
  icon: mdi:harddisk
  unit_of_measurement: '%'
  value_template: '{{ value_json.fs[1].percent }}'

- platform: rest
  scan_interval: 300
  resource: !secret mediacenter_glances
  name: 'MediaCenter TV'
  icon: mdi:harddisk
  unit_of_measurement: '%'
  value_template: '{{ value_json.fs[2].percent }}'

######## OFFICE MOTION SENSOR ########
- platform: mqtt
  name: "Office Motion Sensor"
  command_topic: "smartthings/Office Motion Sensor/motion"
  state_topic: "smartthings/Office Motion Sensor/motion"
  qos: 0
  payload_on: "active"
  payload_off: "inactive"
  retain: true

######## RING DOORBELL MONITORING ########
- platform: ring
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - volume  