######## SWITCHES ########

######## KELLIE DOOR CODE ########
- platform: mqtt
  name: "Kellie Door Code"
  command_topic: "smartthings/Kellie Door Code/switch"
  state_topic: "smartthings/Kellie Door Code/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## ANDREA DOOR CODE ########
- platform: mqtt
  name: "Andrea Door Code"
  command_topic: "smartthings/Andrea Door Code/switch"
  state_topic: "smartthings/Andrea Door Code/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## ROBERT DOOR CODE ########
- platform: mqtt
  name: "Robert Door Code"
  command_topic: "smartthings/Robert Door Code/switch"
  state_topic: "smartthings/Robert Door Code/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## OFFICE WALL SWITCH ########
- platform: mqtt
  name: "Office Switch"
  command_topic: "smartthings/Office Switch/switch"
  state_topic: "smartthings/Office Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true  

######## LIVING ROOM WALL SWITCH ########
- platform: mqtt
  name: "Front Room Switch"
  command_topic: "smartthings/Front Room Switch/switch"
  state_topic: "smartthings/Front Room Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true    

######## MASTER BEDROOM WALL SWITCH ########
- platform: mqtt
  name: "Master Bedroom Switch"
  command_topic: "smartthings/Master Bedroom Switch/switch"
  state_topic: "smartthings/Master Bedroom Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true    

######## ANDREA WALL SWITCH ########
- platform: mqtt
  name: "Andrea Switch"
  command_topic: "smartthings/Andrea Switch/switch"
  state_topic: "smartthings/Andrea Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true   

######## BRENDAN WALL SWITCH ########
- platform: mqtt
  name: "Brendan Switch"
  command_topic: "smartthings/Brendan Switch/switch"
  state_topic: "smartthings/Brendan Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## BACKROOM WALL SWITCH ########
- platform: mqtt
  name: "Back Room Switch"
  command_topic: "smartthings/Back Room Switch/switch"
  state_topic: "smartthings/Back Room Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## DOWNSTAIRS HALLWAY SWITCH ########
- platform: mqtt
  name: "Downstairs Hallway Switch"
  command_topic: "smartthings/Downstairs Hallway Switch/switch"
  state_topic: "smartthings/Downstairs Hallway Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## FRONT ROOM CEILING SWITCH ########
- platform: mqtt
  name: "Front Room Ceiling Switch"
  command_topic: "smartthings/Front Room Ceiling Switch/switch"
  state_topic: "smartthings/Front Room Ceiling Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

######## FRONT ROOM SWITCH ########
- platform: mqtt
  name: "Front Room Switch"
  command_topic: "smartthings/Front Room Switch/switch"
  state_topic: "smartthings/Front Room Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true    

######## PORCH SWITCH ########
- platform: mqtt
  name: "Porch Switch"
  command_topic: "smartthings/Porch Switch/switch"
  state_topic: "smartthings/Porch Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true    

######## STAIRS SWITCH ########
- platform: mqtt
  name: "Stairs Switch"
  command_topic: "smartthings/Stairs Switch/switch"
  state_topic: "smartthings/Stairs Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true    

######## UPSTAIRS HALLWAY SWITCH ########
- platform: mqtt
  name: "Upstairs Hallway Switch"
  command_topic: "smartthings/Upstairs Hallway Switch/switch"
  state_topic: "smartthings/Upstairs Hallway Switch/switch"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true    