########Notification when Robert arrives########
alias: Robert arrives home
initial_state: True
hide_entity: False
trigger:
  platform: mqtt
  topic: "smartthings/Robert Door Code/switch"
  payload: "on"
action:
  - service: notify.slack
    data:
      message: "Robert has arrived home."
  - service:  media_player.turn_on
    entity_id: media_player.living_room_home
  - service:  media_player.volume_set
    entity_id: medmedia_player.living_room_home
    data:
      volume_level: 1
  - service: tts.google_say
    entity_id: media_player.living_room_home
    data_template:
      message: >
        {% if now().strftime("%H") | float > 17 %} Good Evening {% elif now().strftime("%H") | float > 12 %} Good afternoon {% else %} Good morning {% endif %} master.  The current time is {{ now().strftime("%l:%M %p") }}. Thermostat is currently {{ states("climate.downstairs") }}.  The current temperature outside is {{ states("sensor.dark_sky_temperature") | round(0) }}°F while it is a comfortable {{ states("sensor.downstairs_thermostat_temperature")  | round(0) }}°F inside.  The current download speed is {{ states("sensor.speedtest_download")  | round(0) }} megabits per second. Andrea is currently {% if is_state('device_tracker.90e7c4e82d12', 'home') %}home{% else %}not home{% endif %}.
  - service: mqtt.publish
    data:
      topic: "smartthings/Robert Door Code/switch"
      payload: "off"