########Turn On Office Lights when motion is detected########
alias: Turn On Office Lights when motion is detected
trigger:
  platform: state
  entity_id: switch.office_motion_sensor
  to: 'on'
action:
  service: light.turn_on
  entity_id: light.office_desk_light, light.office_front_light