########Turn Off Office Lights 5 min after no motion########
alias: Turn Off Office Lights 5 min after no motion
trigger:
  platform: state
  entity_id: sensor.office_motion_sensor
  to: 'off'
  for:
    minutes: 5
action:
  service: switch.turn_off
  entity_id: switch.office_switch