########Adjust Hallway Brightness########
alias: Hallway Lights - Adjust Brightness
trigger:
  platform: state
  entity_id: input_slider.hallway_brightness
action:
  - service: light.turn_on
    data_template:
      entity_id: light.hall_bathroom_light, light.hall_office_light
      brightness: '{{ trigger.to_state.state | int }}'