########Adjust Office Brightness########
alias: Office Lights - Adjust Brightness
trigger:
  platform: state
  entity_id: input_slider.office_brightness
action:
  - service: light.turn_on
    data_template:
      entity_id: light.office_desk_light, light.office_front_light
      brightness: '{{ states.input_slider.office_brightness.state | int }}'